version: "3.8"
services:
  ###########################
  #          MYSQL
  ###########################
  mysql:
    image: mysql
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: mediscreen
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 112928Paco!
      MYSQL_PASSWORD: 112928Paco!
    ports:
      - 3307:3306
    volumes:
      - ./mediscreen_mysql:/var/lib/mysql
    networks:
      - web-server
    restart: always
  ###########################
  #         MONGO
  ###########################
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - mediscreen_mongo:/data/db
    networks:
      - web-server
    restart: always
  ###########################
  #         UI API
  ###########################
  ui-api:
    environment:
      - PROXY_PATIENT=patient-api:8081/patient
      - PROXY_HISTORY=history-api:8082/history
      - PROXY_ASSESSMENT=assessment-api:8083/assessment
    build:
      context: ./ui-api
    networks:
      - web-server
    restart: always
    ports:
      - "8080:8080"
    container_name: ui-api
    depends_on:
      - patient-api
      - history-api
  ###########################
  #       PATIENT API
  ###########################
  patient-api:
    build: patient-api
    image: patient-api-1.0.0.jar
    networks:
      - web-server
    restart: always
    ports:
      - "8081:8081"
    container_name: patient-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/mediscreen?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=112928Paco!
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
    depends_on:
      - mysql
  ###########################
  #       HISTORY API
  ###########################
  history-api:
    build: history-api
    image: history-api-1.0.0.jar
    networks:
      - web-server
    restart: always
    ports:
      - "8082:8082"
    container_name: history-api
    depends_on:
      - mongo
  ###########################
  #     ASSESSMENT API
  ###########################


###########################
#        NETWORK
###########################
networks:
  web-server:
    driver: bridge
###########################
#       VOLUMES
###########################
volumes:
  mediscreen_mysql:
  mediscreen_mongo: